<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

defined('MOODLE_INTERNAL') || die();
$string['addlinklabel'] = 'Ajouter une autre option d\'activité liée';
$string['addlinktitle'] = 'Cliquez pour ajouter une autre option d\'activité liée';
$string['areaintro'] = 'Présentation du certificat';
$string['awarded'] = 'Attribué';
$string['awardedto'] = 'Attribué à';
$string['back'] = 'dos';
$string['border'] = 'Bordure';
$string['borderblack'] = 'Noir';
$string['borderblue'] = 'Bleu';
$string['borderbrown'] = 'Brun';
$string['bordercolor'] = 'Lignes de Bordure';
$string['bordercolor_help'] = 'Étant donné que les images peuvent augmenter considérablement la taille du fichier pdf, vous pouvez choisir d\'imprimer une bordure de lignes au lieu d\'utiliser une image de bordure (assurez-vous que l\'option Image de bordure est définie sur Non). L\'option Bordure de Lignes imprimera une belle bordure de trois lignes de largeurs variables dans la couleur choisie.';
$string['bordergreen'] = 'Vert';
$string['borderlines'] = 'Lignes de bordure';
$string['borderstyle'] = 'Image de Bordures';
$string['borderstyle_help'] = 'L\'option Image de Bordures vous permet de choisir une image de bordure dans le dossier certificate/pix/borders. Sélectionnez l\'image de bordure que vous souhaitez autour des bords du certificat ou ne sélectionnez aucune bordure.';
$string['certify'] = 'Il s\'agit de certifier que';
$string['code'] = 'Code';
$string['companycertify'] = 'Ce certificat d\'achèvement reconnaît que';
$string['companydate'] = 'le {$a}';
$string['companydatecap'] = 'le {$a}';
$string['companydetails'] = 'a suivi avec succès le programme de formation en ligne intitulé';
$string['companyscore'] = 'avec un score global de {$a}';
$string['completiondate'] = 'Achèvement du cours';
$string['course'] = 'Pour';
$string['coursegrade'] = 'Note du cours';
$string['coursename'] = 'Cours';
$string['coursetimereq'] = 'Minutes requises en cours';
$string['coursetimereq_help'] = 'Entrez ici le temps minimum, en minutes, pendant lequel un étudiant doit être connecté au cours avant de pouvoir recevoir le certificat.';
$string['credithours'] = 'Heures de crédit';
$string['customtext'] = 'Texte personnalisé';
$string['customtext_help'] = 'Si vous souhaitez que le certificat imprime des noms différents pour l\'enseignant que ceux qui ont le rôle d\'enseignant, ne sélectionnez pas Imprimer l\'enseignant ni aucune image de signature à l\'exception de l\'image de la ligne. Entrez les noms des enseignants dans cette zone de texte tels que vous souhaitez qu\'ils apparaissent. Par défaut, ce texte est placé en bas à gauche du certificat. Les balises html suivantes sont disponibles&nbsp;: &lt;br&gt;, &lt;p&gt;, &lt;b&gt;, &lt;i&gt;, &lt;u&gt;, &lt;img&gt; (src et largeur ou hauteur obligatoires), &lt;a&gt; (href obligatoire), &lt;font&gt; (couleur, code hexadécimal, police).';
$string['date'] = 'Au';
$string['datefmt'] = 'Format de date';
$string['datefmt_help'] = 'Choisissez un format de date pour imprimer la date sur le certificat ou utilisez le format de la langue de l\'utilisateur.';
$string['datehelp'] = 'Date';
$string['deletissuediomadcertificates'] = 'Supprimer les certificats émis';
$string['delivery'] = 'Distribution';
$string['delivery_help'] = 'Choisissez comment les étudiants obtiennent leur certificat.';
$string['designoptions'] = 'Options de conception';
$string['download'] = 'Forcer le téléchargement';
$string['emailiomadcertificate'] = 'Email';
$string['emailothers'] = 'Envoyer d\'autres e-mails';
$string['emailothers_help'] = 'Adresses e-mail (séparées par des virgules) à notifier lors de l\'émission d\'un certificat.';
$string['emailstudenttext'] = 'Vous trouverez ci-joint votre certificat pour {$a->course}.';
$string['emailteachermail'] = '{$a->student} a reçu son certificat : \'{$a->certificate}\' pour {$a->course}. Vous pouvez le consulter ici : {$a->url}';
$string['emailteachermailhtml'] = '{$a->student} a reçu son certificat : \'<i>{$a->certificate}</i>\' pour {$a->course}. Vous pouvez le consulter ici : <a href="{$a->url}">Rapport de certificat</a>.';
$string['emailteachers'] = 'Envoyer un e-mail aux enseignants';
$string['emailteachers_help'] = 'Avertir les enseignants par e-mail lors de l\'émission d\'un certificat.';
$string['entercode'] = 'Entrez le code du certificat pour vérifier :';
$string['fontsans'] = 'Famille de polices sans empattement';
$string['fontsans_desc'] = 'Famille de polices sans empattement pour les certificats avec polices intégrées';
$string['fontserif'] = 'Famille de polices avec empattement';
$string['fontserif_desc'] = 'Famille de polices avec empattement pour les certificats avec polices intégrées';
$string['getiomadcertificate'] = 'Obtenez votre certificat';
$string['grade'] = 'Note';
$string['gradedate'] = 'Date de la note';
$string['gradefmt'] = 'Format de note';
$string['gradefmt_help'] = 'Formats disponibles : pourcentage, points ou lettre.';
$string['gradeletter'] = 'Note par lettre';
$string['gradepercent'] = 'Note en pourcentage';
$string['gradepoints'] = 'Note en points';
$string['imagetype'] = 'Type d\'image';
$string['incompletemessage'] = 'Pour télécharger votre certificat, vous devez d\'abord terminer toutes les activités requises.';
$string['intro'] = 'Introduction';
$string['iomadcertificate'] = 'Vérification du code de certificat :';
$string['iomadcertificate:addinstance'] = 'Ajouter une instance de certificat';
$string['iomadcertificate:manage'] = 'Gérer une instance de certificat';
$string['iomadcertificate:printteacher'] = 'Être listé comme enseignant sur le certificat';
$string['iomadcertificate:student'] = 'Récupérer un certificat';
$string['iomadcertificate:view'] = 'Voir un certificat';
$string['iomadcertificate:viewother'] = 'Afficher le certificat d\'un autre utilisateur';
$string['iomadcertificatename'] = 'Nom du certificat';
$string['iomadcertificatereport'] = 'Rapport sur les certificats';
$string['iomadcertificatesfor'] = 'Certificats pour';
$string['iomadcertificatetype'] = 'Type de certificat';
$string['iomadcertificatetype_help'] = 'Définit la mise en page et les polices du certificat.';
$string['issued'] = 'Délivré';
$string['issueddate'] = 'Date de délivrance';
$string['issueoptions'] = 'Options d\'émission';
$string['landscape'] = 'Paysage';
$string['lastviewed'] = 'Dernière consultation :';
$string['letter'] = 'Lettre';
$string['lockingoptions'] = 'Options de verrouillage';
$string['modulename'] = 'Certificat Iomad';
$string['modulenameplural'] = 'Certificats Iomad';
$string['modulename_help'] = 'Génération dynamique de certificats selon des conditions définies.';
$string['myiomadcertificates'] = 'Mes certificats';
$string['nofileselected'] = 'Vous devez choisir un fichier à télécharger !';
$string['nogrades'] = 'Aucune note disponible';
$string['noiomadcertificates'] = 'Aucun certificat';
$string['noiomadcertificatesissued'] = 'Aucun certificat délivré';
$string['noiomadcertificatesreceived'] = 'Aucun certificat reçu.';
$string['notapplicable'] = 'N/A';
$string['notfound'] = 'Le numéro de certificat n\'a pas pu être validé.';
$string['notissued'] = 'Non délivré';
$string['notissuedyet'] = 'Pas encore délivré';
$string['notreceived'] = 'Vous n\'avez pas reçu ce certificat';
$string['openbrowser'] = 'Ouvrir dans une nouvelle fenêtre';
$string['opendownload'] = 'Télécharger le certificat';
$string['openemail'] = 'Envoyer le certificat par e-mail';
$string['openwindow'] = 'Ouvrir le certificat';
$string['or'] = 'Ou';
$string['orientation'] = 'Orientation';
$string['orientation_help'] = 'Choisir portrait ou paysage.';
$string['pluginadministration'] = 'Gestion des certificats Iomad';
$string['pluginname'] = 'Certificats Iomad';
$string['portrait'] = 'Portrait';
$string['printdate'] = 'Date d\'impression';
$string['printdate_help'] = 'Date imprimée sur le certificat.';
$string['printerfriendly'] = 'Version imprimable';
$string['printgrade'] = 'Imprimer la note';
$string['printgrade_help'] = 'Choisir l\'élément de note à imprimer.';
$string['printhours'] = 'Imprimer les heures de crédit';
$string['printhours_help'] = 'Nombre d\'heures à imprimer.';
$string['printnumber'] = 'Imprimer le code';
$string['printnumber_help'] = 'Code unique imprimé sur le certificat.';
$string['printoutcome'] = 'Imprimer le résultat';
$string['printoutcome_help'] = 'Imprimer le résultat du cours.';
$string['printseal'] = 'Sceau ou logo';
$string['printseal_help'] = 'Image du sceau ou du logo.';
$string['printsignature'] = 'Signature';
$string['printsignature_help'] = 'Image de signature.';
$string['printteacher'] = 'Imprimer le nom de l\'enseignant';
$string['printteacher_help'] = 'Configurer les rôles enseignants à imprimer.';
$string['printwmark'] = 'Filigrane';
$string['printwmark_help'] = 'Image de filigrane en arrière-plan.';
$string['receivedcerts'] = 'Certificats reçus';
$string['receiveddate'] = 'Date de réception';
$string['removecert'] = 'Supprimer les certificats délivrés';
$string['report'] = 'Rapport';
$string['reportcert'] = 'Rapport de certificats';
$string['reportcert_help'] = 'Afficher les informations du certificat dans les rapports.';
$string['requiredtimenotmet'] = 'Vous devez passer au moins {$a->requiredtime} minutes dans le cours.';
$string['requiredtimenotvalid'] = 'Le temps requis doit être supérieur à 0';
$string['reviewiomadcertificate'] = 'Vérifier votre certificat';
$string['savecert'] = 'Enregistrer les certificats';
$string['savecert_help'] = 'Enregistrer une copie PDF pour chaque utilisateur.';
$string['seal'] = 'Sceau';
$string['sigline'] = 'Ligne';
$string['signature'] = 'Signature';
$string['statement'] = 'a terminé le cours';
$string['summaryofattempts'] = 'Résumé des certificats précédemment reçus';
$string['textoptions'] = 'Options de texte';
$string['title'] = 'CERTIFICAT DE RÉALISATION';
$string['to'] = 'Attribué à';
$string['typeA4_embedded'] = 'A4 intégré';
$string['typeA4_non_embedded'] = 'A4 non intégré';
$string['typeletter_embedded'] = 'Lettre intégrée';
$string['typeletter_non_embedded'] = 'Lettre non intégrée';
$string['unsupportedfiletype'] = 'Le fichier doit être au format JPEG ou PNG';
$string['uploadimage'] = 'Télécharger une image';
$string['uploadimagedesc'] = 'Téléverser des images pour les certificats.';
$string['userdateformat'] = 'Format de date de l\'utilisateur';
$string['validate'] = 'Vérifier';
$string['verifyiomadcertificate'] = 'Vérifier le certificat';
$string['viewed'] = 'Certificat reçu le :';
$string['viewiomadcertificateviews'] = 'Afficher {$a} certificats émis';
$string['viewtranscript'] = 'Afficher les certificats';
$string['watermark'] = 'Watermark';